"""Single-model CFA fitting, permutation invariance testing, and fit-criteria helpers.

All invariance-level models are generated by semTools::measEq.syntax with
ID.cat = "Wu.Estabrook.2016" and ID.fac = "std.lv" (see measeq.py for why
plain ``group.equal`` shortcuts are vacuous for ordinal indicators). The
level ladder for ordinal data is:

    configural -> thresholds -> metric -> scalar -> strict

per Wu & Estabrook (2016), and assert_level_adds_df guards every
permuteMeasEq delta test against silently vacuous comparisons.
"""
import numpy as np

from .r_env import RRuntimeError, ro, semtools, set_seeds
from .measeq import (LEVEL_NEW_PARAMS, WU_ESTABROOK_LEVELS,
                     assert_level_adds_df, fit_measeq_level)

LEVEL_NAMES = [name for name, _ in WU_ESTABROOK_LEVELS]
LEVEL_GROUP_EQUAL = dict(WU_ESTABROOK_LEVELS)

# display names used in log prints ('CONFIG' predates the measEq rewrite and
# is kept so old and new logs stay grep-compatible)
_LEVEL_PRINT = {
    'configural': 'CONFIG',
    'thresholds': 'THRESHOLDS',
    'metric': 'METRIC',
    'scalar': 'SCALAR',
    'strict': 'STRICT',
}


def build_cfa_cmd(ordered, parameterization="theta", group_equal=None):
    """Build a plain R ``cfa(...)`` command string.

    WARNING: for ordinal indicators, ``group_equal`` values beyond
    "loadings" do NOT produce testable models (intercepts/residuals are
    already fixed; see measeq.py and HANDOFF_measeq_fix.md). Kept only for
    fitting unconstrained/configural models outside the invariance ladder;
    every invariance-level fit must go through fit_measeq_level instead.

    Parameters
    ----------
    ordered : True or iterable of str
        True renders ``ordered = TRUE``; an iterable of item names renders
        ``ordered = c("item1", ...)``.
    parameterization : str or None
        None omits the argument entirely (lavaan defaults to delta).
    group_equal : None, str, or list of str
        Constraints for the invariance level being fit.
    """
    parts = ['cfa(testformula_r, data = rdata, group = group, estimator = "WLSMV"']
    if parameterization is not None:
        parts.append(f'parameterization = "{parameterization}"')
    if group_equal is not None:
        if isinstance(group_equal, str):
            parts.append(f'group.equal = "{group_equal}"')
        else:
            ge_str = ', '.join(f'"{g}"' for g in group_equal)
            parts.append(f'group.equal = c({ge_str})')
    if ordered is True:
        parts.append('ordered = TRUE')
    else:
        ordered_str = ', '.join(f'"{i}"' for i in ordered)
        parts.append(f'ordered = c({ordered_str})')
    return ', '.join(parts) + ')'


def push_model_to_r(scalename, list_of_items, mydata_python, mydata_temp_path):
    """Send the lavaan formula, data (via a temp csv), and group column to R."""
    myrstring = scalename + " =~ " + " + ".join(list_of_items)
    ro.globalenv['testformula_r'] = myrstring
    # transfer data from python into R by way of a csv file
    mydata_python.to_csv(mydata_temp_path)
    ro.r(f'rdata <- read.csv("{mydata_temp_path}", header = TRUE)')
    ro.globalenv['group'] = 'whichdata'


def permute_measeq_with_retry(num_iter, cpus_to_use, **kwargs):
    """Run semTools::permuteMeasEq with the retry-with-fewer-cores fallbacks.

    permuteMeasEq's multicore path sometimes crashes in forked workers
    (LAPACK dgesdd); retry with half the workers, then serially. This is the
    single permutation entry point for the whole package so every caller
    gets the same fallbacks.
    """
    try:
        return semtools.permuteMeasEq(
            nPermute=num_iter, parallelType="multicore", ncpus=cpus_to_use,
            **kwargs)
    except RRuntimeError:
        try:
            return semtools.permuteMeasEq(
                nPermute=num_iter, parallelType="multicore",
                ncpus=cpus_to_use // 2, **kwargs)
        except RRuntimeError:
            return semtools.permuteMeasEq(
                nPermute=num_iter, parallelType="no", ncpus=cpus_to_use // 2,
                **kwargs)


def print_summary(obj):
    rprint = ro.r('print')
    summary = ro.r('summary')
    return rprint(summary(obj))


def print_short_summary(invariance_output):
    ro.r("myoutput <- capture.output(summary(invariance_output))")
    ro.r("stringid <- grep(\"chisq\", myoutput)")
    ro.r("print(myoutput[stringid-1])")
    ro.r("print(myoutput[stringid])")
    return (0)


def print_problematic_items(invariance_output):
    ro.r("myoutput <- capture.output(summary(invariance_output))")
    print('Problematic items:')
    ro.r("stringidsig <- grep(\"may differ between Groups\", myoutput)")
    ro.r("print(myoutput[stringidsig])")
    return (0)


def extract_p(invariance_output):
    ro.globalenv['invariance_output'] = invariance_output
    ro.r("myoutput <- capture.output(summary(invariance_output))")
    ro.r("stringid <- grep(\"chisq\", myoutput)")
    ro.r('myrline <- myoutput[stringid]')
    mypline = ro.r('myrline')[0]
    my_p = mypline.split()[-1]
    return(my_p)


def nafloat(x):
    try:
        x = float(x)
    except ValueError:
        x = np.nan
    return x


def check_secondary_criteria(fit_config):
    Criteria_passed = False
    ro.globalenv['fit_config'] = fit_config
    ro.r("myoutputconfig <- capture.output(summary(fit_config, fit.measures=TRUE))")
    ro.r("stringid_cfi <- grep(\"Robust.*CFI\", myoutputconfig)")
    ro.r("cfi_line <- myoutputconfig[stringid_cfi]")
    cfiline = ro.r('cfi_line')[0]
    my_cfi = cfiline.split()[-1]
    my_cfi = nafloat(my_cfi)
    ro.r("stringid_tli <- grep(\"Robust.*TLI\", myoutputconfig)")
    ro.r("tli_line <- myoutputconfig[stringid_tli]")
    tliline = ro.r('tli_line')[0]
    my_tli = tliline.split()[-1]
    my_tli = nafloat(my_tli)
    ro.r("stringid_rmsea <- grep(\"Robust.*RMSEA\", myoutputconfig)")
    ro.r("rmsea_line <- myoutputconfig[stringid_rmsea]")
    myrmsealine = ro.r('rmsea_line')[0]
    my_rmsea = myrmsealine.split('\n')[0].split()[-1]
    my_rmsea = nafloat(my_rmsea)
    if (my_cfi > 0.95) and (my_tli > 0.95) and (my_rmsea < 0.06):
        Criteria_passed = True
    return (Criteria_passed, my_cfi, my_tli, my_rmsea)


def cfa_levels(whichcfa):
    """Return the ordered list of Wu-Estabrook levels tested up to and
    including ``whichcfa``. Configural is always included first.

    >>> cfa_levels('metric')
    ['configural', 'thresholds', 'metric']
    """
    if whichcfa not in LEVEL_NAMES:
        raise ValueError(
            f"unknown whichcfa {whichcfa!r}; choose from {LEVEL_NAMES}")
    return LEVEL_NAMES[:LEVEL_NAMES.index(whichcfa) + 1]


def cfa_helper_func(scalename, list_of_items, mydata_python, mydata_temp_path,
                    num_iter, cpus_to_use, max_level='strict',
                    parameterization="theta"):
    # Helper CFA funct
    # Inputs:
    # --> scalename - string of scale name: 'appetite_loss'
    # --> list_of_items - list of items to test, not necessarily the full list of items for the scale: ['hitop280', 'hitop283', 'hitop109']
    # --> mydata_python - python df with data (this function will feed it to R)
    # --> mydata_temp_path - path to do an intermediate step of saving from python, then reading into R
    # --> num_iter - permutations for permuteMeasEq
    # --> cpus_to_use - workers for permuteMeasEq
    # --> max_level - highest Wu-Estabrook level to test ('thresholds',
    #     'metric', 'scalar', or 'strict'); lower levels are always tested
    #     first and the ladder stops at the first failure
    # --> parameterization - "theta" (project default) or "delta"
    #
    # Every level is fit via semTools::measEq.syntax (Wu-Estabrook 2016,
    # ID.fac = "std.lv"); the items are always declared ordered by name
    # (measEq.syntax requires explicit names, ordered = TRUE is not
    # supported). assert_level_adds_df runs before every delta test.
    #
    # Returns (flag_passed_metric, config_p, thresholds_p, metric_p,
    # scalar_p, strict_p); p-values are the strings parsed by extract_p,
    # 'NA' for untested levels.

    # SETTING THE SEED HERE, JUST TO BE SURE IT IS SET TO THE SAME THING EVERY TIME I RUN THIS HELPER FUNCTION
    set_seeds(12345)

    push_model_to_r(scalename, list_of_items, mydata_python, mydata_temp_path)

    levels_to_test = cfa_levels(max_level)
    ps = {name: 'NA' for name in LEVEL_NAMES}
    flag_passed_metric = False  # metric is the most important level --> we return this

    # Always do CONFIGURAL:
    fit_config = fit_measeq_level(list_of_items, group_equal=None,
                                  parameterization=parameterization,
                                  r_fit_name='fit_configural')
    # In the case of testing configural invariance when modelType = "mgcfa",
    # con is the configural model (implicitly, the unconstrained model is the
    # saturated model, so use the defaults uncon = NULL and param = NULL).
    out_config = permute_measeq_with_retry(num_iter, cpus_to_use,
                                           con=fit_config)
    config_p = extract_p(out_config)
    ps['configural'] = config_p
    if float(config_p) >= 0.05:
        print('CONFIG INVARIANT chisq p = ' + str(config_p))
        flag_passed_config = True
    else:
        (flag_passed_config, my_cfi, my_tli, my_rmsea) = check_secondary_criteria(fit_config)
        if flag_passed_config:
            print('CONFIG chisq p = ' + str(config_p))
            print('PASSED SECONDARY CRITERIA WITH CFI = ' + str(my_cfi) + ' TLI = ' + str(my_tli) + ' RMSEA = ' + str(my_rmsea))
        else:
            print('CONFIG chisq p = ' + str(config_p))
            print('FAILED SECONDARY CRITERIA WITH CFI = ' + str(my_cfi) + ' TLI = ' + str(my_tli) + ' RMSEA = ' + str(my_rmsea))
            print('CONFIG INVARIANT NOT PASSED, chisq p = ' + str(config_p))

    # Climb the ladder one level at a time; each level is only tested if the
    # previous one passed. permuteMeasEq's param is the constraints the level
    # NEWLY adds (thresholds / loadings / intercepts / residuals).
    if flag_passed_config:
        prev_level = 'configural'
        prev_fit = fit_config
        for level in levels_to_test[1:]:
            fit_level = fit_measeq_level(
                list_of_items, group_equal=LEVEL_GROUP_EQUAL[level],
                parameterization=parameterization, r_fit_name=f'fit_{level}')
            assert_level_adds_df(f'fit_{prev_level}', f'fit_{level}',
                                 prev_level, level)
            new_params = LEVEL_NEW_PARAMS[level]
            param = (new_params[0] if len(new_params) == 1
                     else ro.StrVector(list(new_params)))
            out_level = permute_measeq_with_retry(
                num_iter, cpus_to_use, uncon=prev_fit, con=fit_level,
                param=param)
            level_p = extract_p(out_level)
            ps[level] = level_p
            if float(level_p) >= 0.05:
                print(f'{_LEVEL_PRINT[level]} INVARIANT chisq p = {level_p}')
                if level == 'metric':
                    flag_passed_metric = True
                prev_level, prev_fit = level, fit_level
            else:
                print(f'{_LEVEL_PRINT[level]} INVARIANT NOT PASSED, '
                      f'chisq p = {level_p}')
                break

    # levels never reached (ladder stopped early or max_level below them)
    for level in LEVEL_NAMES[1:]:
        if ps[level] == 'NA':
            print(f'{_LEVEL_PRINT[level]} N/A')

    return (flag_passed_metric, ps['configural'], ps['thresholds'],
            ps['metric'], ps['scalar'], ps['strict'])


def run_specific_cfa(whichscale, item_list, whichcfa, datasets, temp_path,
                     num_iter, cpus_to_use, return_vals=False,
                     parameterization="theta"):
    """Run the pairwise CFA for a specific formula on each dataset pair.

    whichcfa : highest Wu-Estabrook level to test (see cfa_levels).

    datasets : mapping of pair label -> dataframe, e.g.
        {'V_GP': data_val_genpop, 'V_EN': data_val_enriched, 'GP_EN': data_genpop_enriched}
    """
    print(f'\n\nFOR SCALE {whichscale.upper()}:')
    print(f'\nRUN ALL 3-way CFA for items: {item_list}.')

    # validate the requested level up front
    cfa_levels(whichcfa)

    res = []
    flags = []
    for pair, data in datasets.items():
        print(f'\n -----> {pair} <----- ')
        flag_metric, pconfig, pthresholds, pmetric, pscalar, pstrict = cfa_helper_func(
                        scalename=whichscale,
                        list_of_items=item_list,
                        mydata_python=data,
                        mydata_temp_path=temp_path,
                        num_iter=num_iter,
                        cpus_to_use=cpus_to_use,
                        max_level=whichcfa,
                        parameterization=parameterization)
        flags.append(flag_metric)
        row = dict(
            pair=pair,
            pconfig=pconfig,
            pthresholds=pthresholds,
            pmetric=pmetric,
            pscalar=pscalar,
            pstrict=pstrict
        )
        res.append(row)

    if all(flags):
        print("\n!!! PASSES 3-WAY INVARIANCE")

    print("DONE")
    if return_vals:
        return res
    else:
        return(0)
