# =============================================================================
# Stepwise CFA targeting scalar invariance (v4, measEq).
#
# The invariance target is SCALAR (thresholds + loadings + intercepts under
# Wu & Estabrook 2016), continuing from each metric core; the clinical-vs-HV
# latent mean comparisons are only valid under scalar invariance. All models
# are generated by semTools::measEq.syntax (ID.cat = "Wu.Estabrook.2016",
# ID.fac = "std.lv"); under measEq the intercepts level genuinely
# constrains item intercepts and frees the group-2 latent mean, so the
# op "~1" intercept-MI extractor is valid again (unlike the old vacuous
# pipeline). assert_level_adds_df runs before every permuteMeasEq delta
# test.
#
# Resume-from-metric-run: the metric notebook saves per-scale histories as
# ``cfa_dir / f'{scale}_history.pkl'`` and a summary as
# ``cfa_dir / 'stepwise.pkl'``; ``load_metric_run`` reads those and
# ``do_stepwise_scalar_from_metric_run`` wires the metric core straight into
# the scalar search. These pickles MUST be measEq-era outputs: all
# pre-measEq pickles were deleted when the vacuous-scalar bug was found
# (HANDOFF_measeq_fix.md), so this is safe by construction -- never point
# load_metric_run at archived pre-measEq results.
#
# Because the metric run already verified configural + thresholds + metric
# invariance for the core (same data, same seeds, same parameterization),
# the first iteration skips the lower-level permutation tests and runs only
# the scalar test (``assume_metric_invariant=True``). The models are still
# fit (permuteMeasEq needs the lavaan objects and the df ladder is still
# asserted); only the redundant permutation tests are skipped. History rows
# record ``lower_levels_assumed=True`` for transparency. Set
# ``assume_metric_invariant=False`` to re-verify everything.
#
# Under std.lv identification there is NO marker item: every item has
# testable loading/intercept MIs and every item is an ablation candidate.
#
# Removal logic by level:
#   - configural regression (defensive)  -> combinatorial ablation
#     (all_config_passed filter, CFI -> TLI -> RMSEA cascade)
#   - thresholds regression (defensive)  -> single-item threshold-MI removal
#   - metric regression (defensive)      -> single-item loading-MI removal
#   - scalar failure (the main case)     -> single-item intercept-MI removal
# =============================================================================
from itertools import combinations
from pathlib import Path

import numpy as np
import pandas as pd

from .r_env import localconverter, pandas2ri, ro, set_seeds
from .fit import (check_secondary_criteria, extract_p,
                  permute_measeq_with_retry, push_model_to_r)
from .measeq import (WU_ESTABROOK_LEVELS, assert_level_adds_df,
                     extract_item_mis_from_thresholds, fit_measeq_level)
from .stepwise_metric import (DEFAULT_CFI_TIE_TOLERANCE,
                              DEFAULT_TLI_TIE_TOLERANCE,
                              _mi_removal_step, _pick_by_cascade,
                              extract_item_mis_from_metric, find_worst_item)

_GROUP_EQUAL = dict(WU_ESTABROOK_LEVELS)


# -----------------------------------------------------------------------------
# Loading a completed metric stepwise run
# -----------------------------------------------------------------------------
def load_metric_run(cfa_dir, scale):
    """Load the metric-invariant core for ``scale`` from a completed metric
    stepwise run.

    Looks for ``cfa_dir / f'{scale}_history.pkl'`` first (the per-scale
    history written by the metric loop in NB_2_cfa_as_reg). If that file is
    missing, falls back to the ``stepwise.pkl`` summary (or
    ``stepwise_in_progress.pkl`` if the final summary isn't there).

    The pickles must come from a measEq-era metric run (all pre-measEq
    pickles were deleted; do not resurrect them from archives).

    Returns
    -------
    metric_core : list[str] or None
        The metric-invariant item set, or None if the metric run did not
        find one for this scale.
    metric_history : pd.DataFrame or None
        The full metric history when loaded from the per-scale pickle;
        None when only the summary was available.
    """
    cfa_dir = Path(cfa_dir)

    hist_path = cfa_dir / f'{scale}_history.pkl'
    if hist_path.exists():
        history = pd.read_pickle(hist_path)
        success = history[history['action'] == 'success']
        if len(success) == 0:
            return None, history
        return list(success.iloc[-1]['items']), history

    for summary_name in ('stepwise.pkl', 'stepwise_in_progress.pkl'):
        summary_path = cfa_dir / summary_name
        if summary_path.exists():
            summary = pd.read_pickle(summary_path)
            row = summary[summary['scale'] == scale]
            if len(row) == 0:
                continue
            item_nos = row.iloc[-1].get('item_nos')
            if item_nos is None or (np.isscalar(item_nos) and pd.isna(item_nos)):
                return None, None
            return list(item_nos), None

    raise FileNotFoundError(
        f"No metric run found for {scale!r} in {cfa_dir} "
        f"(looked for {scale}_history.pkl, stepwise.pkl, "
        f"stepwise_in_progress.pkl)")


# -----------------------------------------------------------------------------
# Hierarchical CFA test for ONE pairwise comparison, up to scalar.
# -----------------------------------------------------------------------------
def cfa_test_scalar_with_mi(scalename, list_of_items, mydata_python, mydata_temp_path,
                            num_iter, cpus_to_use, max_level='scalar',
                            parameterization="theta",
                            skip_lower_tests=False):
    """
    Test one dataset pair up the Wu-Estabrook ladder
    configural -> thresholds -> metric -> scalar, stopping at the first
    failed level or at ``max_level``. Every model comes from
    semTools::measEq.syntax and assert_level_adds_df guards every delta
    test.

    Parameters
    ----------
    max_level : {'configural', 'thresholds', 'metric', 'scalar'}
        Highest invariance level to test. Lower levels are always tested
        first; the test sequence stops at the first failure or at max_level.
    skip_lower_tests : bool
        If True, fit the configural/thresholds/metric models but skip their
        permutation tests, treating those levels as passed. Only valid when
        the caller has already verified them for exactly these items on
        exactly this data (e.g. resuming from a completed measEq-era metric
        stepwise run: fixed seeds make the skipped tests deterministic
        re-runs). The df ladder is still asserted at every level.
        config_p / thresholds_p / metric_p are recorded as NaN.

    Returns
    -------
    dict with keys:
        config_p, config_passed, config_passed_primary,
        config_cfi, config_tli, config_rmsea,
        thresholds_p, thresholds_passed, thresholds_item_mis,
        metric_p, metric_passed, metric_item_mis,
        scalar_p, scalar_passed, scalar_item_mis,
        lower_levels_assumed
    thresholds_item_mis holds the THRESHOLD-equality MIs (op == "|"),
    metric_item_mis the LOADING MIs (op == "=~"), and scalar_item_mis the
    INTERCEPT MIs (op == "~1"); each is populated only when its level
    failed.
    """
    set_seeds(12345)

    push_model_to_r(scalename, list_of_items, mydata_python, mydata_temp_path)

    # ----- Configural -----
    # The configural model must be fit even when skipping its permutation
    # test: the df-ladder assertions and permuteMeasEq need the lavaan
    # objects.
    fit_config = fit_measeq_level(list_of_items, group_equal=None,
                                  parameterization=parameterization,
                                  r_fit_name='fit_config')

    if skip_lower_tests:
        config_p = np.nan
        config_passed_primary = True
        config_passed = True
        # fit indices are cheap (no permutations) -- keep them for the record
        _, cfi, tli, rmsea = check_secondary_criteria(fit_config)
    else:
        out_config = permute_measeq_with_retry(num_iter, cpus_to_use,
                                               con=fit_config)
        config_p = float(extract_p(out_config))
        config_passed_primary = (config_p >= 0.05)
        config_passed_secondary, cfi, tli, rmsea = check_secondary_criteria(fit_config)
        config_passed = config_passed_primary or config_passed_secondary

    result = {
        'config_p':              config_p,
        'config_passed':         config_passed,
        'config_passed_primary': config_passed_primary,
        'config_cfi':            cfi,
        'config_tli':            tli,
        'config_rmsea':          rmsea,
        'thresholds_p':          None,
        'thresholds_passed':     None,
        'thresholds_item_mis':   None,
        'metric_p':              None,
        'metric_passed':         None,
        'metric_item_mis':       None,
        'scalar_p':              None,
        'scalar_passed':         None,
        'scalar_item_mis':       None,
        'lower_levels_assumed':  skip_lower_tests,
    }

    if max_level == 'configural' or not config_passed:
        return result

    # ----- Thresholds -----
    fit_thresholds = fit_measeq_level(list_of_items,
                                      group_equal=_GROUP_EQUAL['thresholds'],
                                      parameterization=parameterization,
                                      r_fit_name='fit_thresholds')
    assert_level_adds_df('fit_config', 'fit_thresholds',
                         'configural', 'thresholds')

    if skip_lower_tests:
        result['thresholds_p'] = np.nan
        result['thresholds_passed'] = True
    else:
        out_thresholds = permute_measeq_with_retry(
            num_iter, cpus_to_use, uncon=fit_config, con=fit_thresholds,
            param="thresholds")
        ro.globalenv['out_thresholds'] = out_thresholds
        thresholds_p = float(extract_p(out_thresholds))
        thresholds_passed = (thresholds_p >= 0.05)
        result['thresholds_p'] = thresholds_p
        result['thresholds_passed'] = thresholds_passed
        if not thresholds_passed:
            result['thresholds_item_mis'] = extract_item_mis_from_thresholds(
                list_of_items)

    if max_level == 'thresholds' or not result['thresholds_passed']:
        return result

    # ----- Metric (thresholds + loadings) -----
    fit_metric = fit_measeq_level(list_of_items,
                                  group_equal=_GROUP_EQUAL['metric'],
                                  parameterization=parameterization,
                                  r_fit_name='fit_metric')
    assert_level_adds_df('fit_thresholds', 'fit_metric',
                         'thresholds', 'metric')

    if skip_lower_tests:
        result['metric_p'] = np.nan
        result['metric_passed'] = True
    else:
        out_metric = permute_measeq_with_retry(
            num_iter, cpus_to_use, uncon=fit_thresholds, con=fit_metric,
            param="loadings")
        ro.globalenv['out_metric'] = out_metric
        metric_p = float(extract_p(out_metric))
        metric_passed = (metric_p >= 0.05)
        result['metric_p'] = metric_p
        result['metric_passed'] = metric_passed
        if not metric_passed:
            result['metric_item_mis'] = extract_item_mis_from_metric(list_of_items)

    if max_level == 'metric' or not result['metric_passed']:
        return result

    # ----- Scalar (thresholds + loadings + intercepts) -----
    fit_scalar = fit_measeq_level(list_of_items,
                                  group_equal=_GROUP_EQUAL['scalar'],
                                  parameterization=parameterization,
                                  r_fit_name='fit_scalar')
    assert_level_adds_df('fit_metric', 'fit_scalar', 'metric', 'scalar')

    out_scalar = permute_measeq_with_retry(
        num_iter, cpus_to_use, uncon=fit_metric, con=fit_scalar,
        param="intercepts")

    ro.globalenv['out_scalar'] = out_scalar
    scalar_p = float(extract_p(out_scalar))
    scalar_passed = (scalar_p >= 0.05)
    result['scalar_p'] = scalar_p
    result['scalar_passed'] = scalar_passed
    if not scalar_passed:
        result['scalar_item_mis'] = extract_item_mis_from_scalar(list_of_items)

    return result


# -----------------------------------------------------------------------------
# Extract per-item INTERCEPT MIs from the scalar model's permuteMeasEq.
# At scalar, the new constraints added on top of metric are intercept
# equalities (op == "~1" in lavaan). Under measEq/Wu-Estabrook the
# non-reference-group intercepts are genuinely free at metric and
# constrained at scalar, so these MIs are meaningful.
# -----------------------------------------------------------------------------
def extract_item_mis_from_scalar(item_list):
    """
    Filter the scalar @MI.obs to intercept constraints only -- those are
    the constraints the scalar level newly adds, whose violations
    characterize scalar misfit specifically.

    Returns dict[item -> max MI across non-reference groups], or None.
    """
    try:
        ro.r('''
            mi_obs <- out_scalar@MI.obs
            pt     <- out_scalar@PT
            mi_obs$par_name <- pt$par[ match(mi_obs$lhs, pt$plabel) ]
            mi_intercepts <- mi_obs[grepl("~1$", mi_obs$par_name), ]
            if (nrow(mi_intercepts) > 0) {
                mi_intercepts$item <- sub("~1$", "", mi_intercepts$par_name)
            }
        ''')
        mi_df_r = ro.r('mi_intercepts')
        with localconverter(ro.default_converter + pandas2ri.converter):
            mi_df = ro.conversion.rpy2py(mi_df_r)

        if mi_df is None or len(mi_df) == 0:
            return None
        mi_df = mi_df[mi_df['item'].isin(item_list)]
        if len(mi_df) == 0:
            return None

        item_mis = mi_df.groupby('item')['X2'].max().to_dict()
        return {k: float(v) for k, v in item_mis.items()}

    except Exception as e:
        print(f"  [WARN] Could not extract intercept MIs from scalar model: {e}")
        return None


def _test_all_pairs_scalar(scalename, items, datasets, temp_path,
                           num_iter, cpus_to_use, max_level='scalar',
                           parameterization="theta", skip_lower_tests=False):
    results = {}
    for name, data in datasets.items():
        results[name] = cfa_test_scalar_with_mi(
            scalename, items, data, temp_path,
            num_iter=num_iter, cpus_to_use=cpus_to_use,
            max_level=max_level, parameterization=parameterization,
            skip_lower_tests=skip_lower_tests)
    return results


def _build_history_row_scalar(iteration, phase, items, candidate_dropped,
                              pair_results, action=None, removed_items=None,
                              removal_reason=None, mis_used=None,
                              cfi_tied_count=None, tli_tied_count=None,
                              ablation_level=None):
    row = {
        'iteration':         iteration,
        'phase':             phase,
        'candidate_dropped': candidate_dropped,
        'n_items':           len(items),
        'items':             tuple(items),
        'ablation_level':    ablation_level,
    }
    cfis, tlis, rmseas = [], [], []
    all_config_passed = True
    all_thresholds_passed = True
    all_metric_passed = True
    all_scalar_passed = True
    thresholds_evaluable = True
    metric_evaluable = True
    scalar_evaluable = True
    lower_assumed = False

    for name, r in pair_results.items():
        row[f'{name}_config_p']              = r['config_p']
        row[f'{name}_config_passed']         = r['config_passed']
        row[f'{name}_config_passed_primary'] = r['config_passed_primary']
        row[f'{name}_config_cfi']            = r['config_cfi']
        row[f'{name}_config_tli']            = r['config_tli']
        row[f'{name}_config_rmsea']          = r['config_rmsea']
        row[f'{name}_thresholds_p']          = r['thresholds_p']
        row[f'{name}_thresholds_passed']     = r['thresholds_passed']
        row[f'{name}_metric_p']              = r['metric_p']
        row[f'{name}_metric_passed']         = r['metric_passed']
        row[f'{name}_scalar_p']              = r['scalar_p']
        row[f'{name}_scalar_passed']         = r['scalar_passed']

        cfis.append(r['config_cfi'])
        tlis.append(r['config_tli'])
        rmseas.append(r['config_rmsea'])
        lower_assumed = lower_assumed or r.get('lower_levels_assumed', False)

        if not r['config_passed']:
            all_config_passed = False
            thresholds_evaluable = False
            metric_evaluable = False
            scalar_evaluable = False
        if r['thresholds_passed'] is None:
            thresholds_evaluable = False
            metric_evaluable = False
            scalar_evaluable = False
        elif not r['thresholds_passed']:
            all_thresholds_passed = False
            metric_evaluable = False
            scalar_evaluable = False
        if r['metric_passed'] is None:
            metric_evaluable = False
            scalar_evaluable = False
        elif not r['metric_passed']:
            all_metric_passed = False
            scalar_evaluable = False
        if r['scalar_passed'] is None:
            scalar_evaluable = False
        elif not r['scalar_passed']:
            all_scalar_passed = False

    row['min_config_cfi']        = min(cfis) if cfis else None
    row['min_config_tli']        = min(tlis) if tlis else None
    row['max_config_rmsea']      = max(rmseas) if rmseas else None
    row['all_config_passed']     = all_config_passed
    row['all_thresholds_passed'] = (all_thresholds_passed
                                    if thresholds_evaluable else None)
    row['all_metric_passed']     = (all_metric_passed if metric_evaluable else None)
    row['all_scalar_passed']     = (all_scalar_passed if scalar_evaluable else None)
    row['lower_levels_assumed']  = lower_assumed
    row['action']                = action
    row['removed_items']         = removed_items
    row['removal_reason']        = removal_reason
    row['cfi_tied_count']        = cfi_tied_count
    row['tli_tied_count']        = tli_tied_count
    row['mis_used']              = mis_used
    return row


def _search_combo_ablation_scalar(whichscale, current, min_items, iteration,
                                  cfi_tie_tolerance, tli_tie_tolerance,
                                  history_rows, datasets, temp_path,
                                  num_iter, cpus_to_use,
                                  parameterization="theta"):
    """
    Search the smallest combo size k such that some k-item ablation
    achieves 3-way configural invariance. ALL items in ``current`` are
    candidates (no marker under std.lv identification). Candidates are
    evaluated configural-only and filtered by all_config_passed before
    the CFI -> TLI -> RMSEA cascade.
    """
    candidates_pool = list(current)
    max_level_combo = len(current) - min_items
    if max_level_combo < 1:
        return None, None, None, None, None

    for level in range(1, max_level_combo + 1):
        n_combos = sum(1 for _ in combinations(candidates_pool, level))
        print(f"  -- Ablation level {level} ({n_combos} combos) --")

        passing = []
        n_evaluated = 0
        for combo in combinations(candidates_pool, level):
            test_items = [i for i in current if i not in combo]

            combo_label = combo if len(combo) > 1 else combo[0]
            print(f"  Trying drop of {combo_label} -> {len(test_items)} items")
            cand_results = _test_all_pairs_scalar(
                whichscale, test_items, datasets, temp_path,
                num_iter, cpus_to_use, max_level='configural',
                parameterization=parameterization)
            cand_row = _build_history_row_scalar(
                iteration, 'ablation_candidate', test_items, combo_label,
                cand_results, action='ablation_candidate_tested',
                ablation_level=level)
            cmc = cand_row['min_config_cfi']
            cmt = cand_row['min_config_tli']
            cmr = cand_row['max_config_rmsea']
            acp = cand_row['all_config_passed']
            history_rows.append(cand_row)
            print(f"    min_cfi={cmc:.4f} min_tli={cmt:.4f} "
                  f"max_rmsea={cmr:.4f} all_config_passed={acp}")

            n_evaluated += 1
            if acp:
                passing.append((combo, cmc, cmt, cmr, acp))

        if passing:
            print(f"  Level {level}: {len(passing)} of {n_evaluated} combos "
                  f"achieve 3-way configural invariance.")
            best, reason, cfi_tc, tli_tc = _pick_by_cascade(
                passing, cfi_tie_tolerance, tli_tie_tolerance)
            return best[0], reason, level, cfi_tc, tli_tc

        print(f"  Level {level}: no combo achieves 3-way configural invariance. "
              f"Expanding to level {level+1}...")

    return None, None, None, None, None


# -----------------------------------------------------------------------------
# Top-level: stepwise removal targeting scalar invariance, starting from
# a set of metric-invariant items.
# -----------------------------------------------------------------------------
def do_three_way_cfa_stepwise_scalar(whichscale,
                                     metric_invariant_items,
                                     datasets, temp_path,
                                     num_iter, cpus_to_use,
                                     min_items=3,
                                     max_iter=None,
                                     cfi_tie_tolerance=DEFAULT_CFI_TIE_TOLERANCE,
                                     tli_tie_tolerance=DEFAULT_TLI_TIE_TOLERANCE,
                                     parameterization="theta",
                                     assume_metric_invariant=True):
    """
    Search for a 3-way scalar invariant subset starting from a metric-
    invariant core, by iteratively removing the item with the largest
    aggregated permuted intercept modification index. Handles regressions
    at lower levels defensively: configural regression triggers bounded
    combinatorial ablation (all_config_passed filter, CFI -> TLI -> RMSEA
    cascade); thresholds regression triggers single-item threshold-MI
    removal; metric regression triggers single-item loading-MI removal.

    Parameters
    ----------
    whichscale : str
    metric_invariant_items : list[str]
        The metric-invariant core from the upstream procedure (e.g. loaded
        via ``load_metric_run``).
    datasets : dict
        pair label -> dataframe for each pairwise comparison.
    min_items : int
    max_iter : int or None
    cfi_tie_tolerance, tli_tie_tolerance : float
        Same semantics as in the metric procedure.
    assume_metric_invariant : bool
        If True (default), the first iteration skips the configural,
        thresholds, and metric permutation tests, since the metric stepwise
        run already verified them for exactly this item set on this data
        with the same seeds. Later iterations (after any removal) always
        run full tests. Set False to re-verify everything from scratch.

    Returns
    -------
    final_items : list[str] or None
    removed_in_order : list[str]
    history : pd.DataFrame
        One row per test (main or ablation candidate). Columns include
        per-pair config/thresholds/metric/scalar pass-fail and p-values,
        aggregate fit indices, ``lower_levels_assumed``, ``removed_items``
        (tuple), ``ablation_level``, and removal decisions. removal_reason
        takes values in {'cfi_max_min', 'tli_tiebreaker',
        'rmsea_tiebreaker', 'thresholds_mi_worst', 'metric_mi_worst',
        'scalar_mi_worst', None}.
    """
    print(f"\n{'='*60}\nSTEPWISE SCALAR: {whichscale.upper()}\n{'='*60}")

    current = list(metric_invariant_items)
    removed = []
    history_rows = []

    if max_iter is None:
        max_iter = len(current) - min_items

    for it in range(max_iter + 1):
        print(f"\n--- Iteration {it}: {len(current)} items ---")
        print(f"Current: {current}")

        if len(current) < min_items:
            print(f"Below minimum of {min_items} items. Stopping.")
            history_rows.append({
                'iteration': it, 'phase': 'final', 'n_items': len(current),
                'items': tuple(current), 'action': 'failed_min_items',
            })
            return None, removed, pd.DataFrame(history_rows)

        # Skip lower-level permutation tests only on the untouched core:
        # the metric run verified exactly these items on this data.
        skip_lower = assume_metric_invariant and it == 0 and not removed
        if skip_lower:
            print("Testing current item set (configural + thresholds + "
                  "metric assumed from completed metric run; scalar test "
                  "only)...")
        else:
            print("Testing current item set up to scalar...")
        main_results = _test_all_pairs_scalar(whichscale, current, datasets,
                                              temp_path, num_iter, cpus_to_use,
                                              max_level='scalar',
                                              parameterization=parameterization,
                                              skip_lower_tests=skip_lower)

        all_config = all(r['config_passed'] for r in main_results.values())
        all_thresholds = all(r['thresholds_passed'] is True
                             for r in main_results.values()) if all_config else False
        all_metric = all(r['metric_passed'] is True
                         for r in main_results.values()) if all_thresholds else False
        all_scalar = all(r['scalar_passed'] is True
                         for r in main_results.values()) if all_metric else False

        # --- Success ---
        if all_config and all_thresholds and all_metric and all_scalar:
            print(f"\n*** 3-way scalar invariance achieved with {len(current)} items ***")
            row = _build_history_row_scalar(it, 'main', current, None,
                                            main_results, action='success')
            history_rows.append(row)
            return current, removed, pd.DataFrame(history_rows)

        # --- Configural regression (defensive): combinatorial ablation ---
        # Can't occur on a skip_lower iteration (config assumed True there);
        # only reachable after an item removal has changed the set.
        if not all_config:
            print("Configural regressed; running combinatorial ablation "
                  "search (all items)...")
            row = _build_history_row_scalar(it, 'main', current, None,
                                            main_results,
                                            action='configural_ablation_starting')
            history_rows.append(row)
            main_row_idx = len(history_rows) - 1

            best_combo, reason, level, cfi_tc, tli_tc = _search_combo_ablation_scalar(
                whichscale, current, min_items, it,
                cfi_tie_tolerance, tli_tie_tolerance, history_rows,
                datasets, temp_path, num_iter, cpus_to_use,
                parameterization=parameterization)

            if best_combo is None:
                print("  No combo at any level achieves 3-way configural "
                      "invariance. Stopping.")
                history_rows[main_row_idx]['action'] = 'failed_no_combo_passes'
                history_rows.append({
                    'iteration': it, 'phase': 'final',
                    'n_items': len(current), 'items': tuple(current),
                    'action': 'failed_no_combo_passes',
                })
                return None, removed, pd.DataFrame(history_rows)

            print(f"  -> Removing combo {best_combo} "
                  f"(ablation_level={level}, reason={reason})")
            history_rows[main_row_idx]['removed_items']   = tuple(best_combo)
            history_rows[main_row_idx]['removal_reason']  = reason
            history_rows[main_row_idx]['ablation_level']  = level
            history_rows[main_row_idx]['cfi_tied_count']  = cfi_tc
            history_rows[main_row_idx]['tli_tied_count']  = tli_tc

            for item in best_combo:
                removed.append(item)
                current.remove(item)
            continue

        # --- Thresholds regression (defensive): threshold-MI removal ---
        if not all_thresholds:
            print("Thresholds regressed; running threshold-MI-based "
                  "removal...")
            failing_mis = [r['thresholds_item_mis']
                           for r in main_results.values()
                           if r['thresholds_passed'] is False
                           and r['thresholds_item_mis']]
            if not _mi_removal_step('threshold', failing_mis, current, removed,
                                    history_rows, it, main_results,
                                    fail_action='failed_no_thresholds_mi',
                                    removal_action='thresholds_mi_removal',
                                    removal_reason='thresholds_mi_worst',
                                    build_row=_build_history_row_scalar):
                return None, removed, pd.DataFrame(history_rows)
            continue

        # --- Metric regression (defensive): single-item loading-MI removal ---
        if not all_metric:
            print("Metric regressed; running loading-MI-based removal...")
            failing_mis = [r['metric_item_mis']
                           for r in main_results.values()
                           if r['metric_passed'] is False
                           and r['metric_item_mis']]
            if not _mi_removal_step('loading', failing_mis, current, removed,
                                    history_rows, it, main_results,
                                    fail_action='failed_no_metric_mi',
                                    removal_action='metric_mi_removal',
                                    removal_reason='metric_mi_worst',
                                    build_row=_build_history_row_scalar):
                return None, removed, pd.DataFrame(history_rows)
            continue

        # --- Scalar failure: intercept MI removal (the main case) ---
        print("Scalar failed; running intercept-MI-based removal...")
        failing_mis = [r['scalar_item_mis'] for r in main_results.values()
                       if r['scalar_passed'] is False and r['scalar_item_mis']]
        if not _mi_removal_step('intercept', failing_mis, current, removed,
                                history_rows, it, main_results,
                                fail_action='failed_no_scalar_mi',
                                removal_action='scalar_mi_removal',
                                removal_reason='scalar_mi_worst',
                                build_row=_build_history_row_scalar):
            return None, removed, pd.DataFrame(history_rows)

    print(f"\nHit max_iter ({max_iter}) without convergence.")
    history_rows.append({
        'iteration': max_iter + 1, 'phase': 'final',
        'n_items': len(current), 'items': tuple(current),
        'action': 'failed_max_iter',
    })
    return None, removed, pd.DataFrame(history_rows)


# -----------------------------------------------------------------------------
# Convenience wrapper: load a completed metric run and continue to scalar.
# -----------------------------------------------------------------------------
def do_stepwise_scalar_from_metric_run(whichscale, cfa_dir,
                                       datasets, temp_path,
                                       num_iter, cpus_to_use,
                                       **kwargs):
    """Load the metric-invariant core for ``whichscale`` from a completed
    measEq-era metric stepwise run (see ``load_metric_run``) and continue
    searching for a scalar-invariant core from there.

    Any additional keyword arguments (min_items, max_iter, tolerances,
    parameterization, assume_metric_invariant) are forwarded to
    ``do_three_way_cfa_stepwise_scalar``.

    Returns
    -------
    final_items : list[str] or None
        None either when the metric run found no invariant core for this
        scale (nothing to continue from) or when the scalar search failed.
    removed_in_order : list[str]
    history : pd.DataFrame
        A one-row DataFrame with action 'no_metric_core' when the metric
        run had no core for this scale; otherwise the scalar history.
    """
    metric_core, _metric_history = load_metric_run(cfa_dir, whichscale)

    if metric_core is None:
        print(f"[{whichscale}] Metric run found no invariant core; "
              f"nothing to continue from.")
        history = pd.DataFrame([{
            'iteration': 0, 'phase': 'final', 'n_items': 0,
            'items': tuple(), 'action': 'no_metric_core',
        }])
        return None, [], history

    print(f"[{whichscale}] Loaded metric-invariant core "
          f"({len(metric_core)} items): {metric_core}")

    return do_three_way_cfa_stepwise_scalar(
        whichscale, metric_core, datasets, temp_path,
        num_iter, cpus_to_use, **kwargs)
